baseURL = 'https://blog.erfun.net/'
languageCode = "fa"
title = 'وبلاگ'
theme = 'paper'
author = "Erfun Kh"
copyright = "© 2024, erfun.net"
paginate = 3
DefaultContentLanguage = "fa"
enableInlineShortcodes = true
ignoreErrors = ["error-remote-getjson"]

[params]
direction = "rtl"

color = 'linen'

github = 'ErFUN-KH'

avatar = 'erfun.kh@gmail.com'
name = 'عرفان'
bio = 'فعلا برای تست اینجا باشه'
# ------------------------------

# needed to  render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
#  [markup.highlight]
#    lineNos = true

[menu]

[[menu.main]]
identifier = "about"
name = "درباره"
url = "/about/"
weight = 10
[[menu.main]]
identifier = "contact"
name = "تماس"
url = "/contact/"
weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

[privacy.vimeo]
disabled = false
simple = true

[privacy.twitter]
disabled = false
enableDNT = true
simple = true

[privacy.instagram]
disabled = false
simple = true

[privacy.youtube]
disabled = false
privacyEnhanced = true

[services]

[services.instagram]
disableInlineCSS = true

[services.twitter]
disableInlineCSS = true
